import io
import pytest
from docx import Document
from src.resume_processor import create_docx, create_cover_letter_docx, read_resume, get_openai_client
from src.prompts.resume_tailor import SYSTEM_PROMPT, USER_PROMPT_TEMPLATE
from src.prompts.cover_letter import COVER_LETTER_SYSTEM_PROMPT, COVER_LETTER_USER_TEMPLATE


def test_create_docx_generation():
    resume_data = {
        "name": "Jane Doe",
        "email": "jane.doe@example.com",
        "phone": "+1 555-123-4567",
        "location": "San Francisco, CA",
        "github": "github.com/janedoe",
        "linkedin": "linkedin.com/in/janedoe",
        "portfolio": "https://janedoe.dev",
        "professional_summary": "Experienced Software Engineer with 5+ years of Python expertise.",
        "work_experience": [
            {
                "title": "Senior Python Developer",
                "company": "Tech Corp",
                "duration": "2021 - Present",
                "bullets": [
                    "Designed scalable microservices using FastAPI.",
                    "Improved API latency by 40%."
                ]
            }
        ],
        "projects": [
            {
                "name": "AI Resume Tailor",
                "bullets": [
                    "Built full-stack AI platform with Streamlit and FastAPI."
                ]
            }
        ],
        "skills": ["Python", "FastAPI", "SQLAlchemy", "Docker"],
        "soft_skills": ["Leadership", "Problem Solving", "Collaboration"],
        "education": [
            {
                "degree": "B.S. in Computer Science",
                "institution": "University of California",
                "year": "2017 - 2021"
            }
        ]
    }

    docx_bytes = create_docx(resume_data)
    assert isinstance(docx_bytes, bytes)
    assert len(docx_bytes) > 0

    # Verify that the generated bytes can be parsed as a valid DOCX document
    doc = Document(io.BytesIO(docx_bytes))
    full_text = "\n".join([p.text for p in doc.paragraphs])
    assert "Jane Doe" in full_text
    assert "Senior Python Developer" in full_text
    assert "Tech Corp" in full_text
    assert "Python" in full_text


def test_create_cover_letter_docx_generation():
    cover_letter_text = (
        "Dear Hiring Manager,\n\n"
        "I am writing to express my strong enthusiasm for the Senior Software Engineer position.\n\n"
        "With over 5 years of experience developing Python microservices, I am confident in my ability to deliver impact.\n\n"
        "Sincerely,\nJane Doe"
    )

    docx_bytes = create_cover_letter_docx(cover_letter_text)
    assert isinstance(docx_bytes, bytes)
    assert len(docx_bytes) > 0

    doc = Document(io.BytesIO(docx_bytes))
    full_text = "\n".join([p.text for p in doc.paragraphs])
    assert "Dear Hiring Manager" in full_text
    assert "Senior Software Engineer" in full_text


def test_read_resume_docx():
    doc = Document()
    doc.add_paragraph("First paragraph of resume.")
    doc.add_paragraph("Second paragraph with experience.")
    buffer = io.BytesIO()
    doc.save(buffer)
    docx_bytes = buffer.getvalue()

    extracted_text = read_resume(docx_bytes, "my_resume.docx")
    assert "First paragraph of resume." in extracted_text
    assert "Second paragraph with experience." in extracted_text


def test_read_resume_invalid_extension():
    with pytest.raises(ValueError, match="File must be .pdf or .docx"):
        read_resume(b"some content", "resume.txt")


def test_prompt_templates_formatting():
    formatted_resume = USER_PROMPT_TEMPLATE.format(
        resume_text="Sample resume text",
        job_description="Sample job description"
    )
    assert "Sample resume text" in formatted_resume
    assert "Sample job description" in formatted_resume

    formatted_cover_letter = COVER_LETTER_USER_TEMPLATE.format(
        resume_text="Sample candidate resume",
        job_description="Target job requirements"
    )
    assert "Sample candidate resume" in formatted_cover_letter
    assert "Target job requirements" in formatted_cover_letter


def test_get_openai_client(monkeypatch):
    monkeypatch.setenv("OPENAI_BASE_URL", "http://localhost:11434/v1")
    client = get_openai_client()
    assert str(client.base_url) == "http://localhost:11434/v1/"
